# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "osc-ruby", "~> 1.1"

gem "securerandom", "~> 0.1.0"
